services:
  - type: web
    name: core-access-api
    env: node
    plan: free
    buildCommand: npm run build
    startCommand: npm run server:prod
    envVars:
      - key: NODE_ENV
        value: production
      - key: DATABASE_URL
        sync: false
