services:
  - type: web
    name: core-access-api
    env: node
    plan: free
    buildCommand: npm install
    startCommand: npm run api:start
    envVars:
      - key: NODE_ENV
        value: production
      - key: DATABASE_URL
        sync: false
