import { StyleSheet } from 'react-native';

export const styles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: 'black',
  },
  gameHeader: {
    paddingTop: 80,
    paddingBottom: 40,
    alignItems: 'center',
    backgroundColor: '#1a1a2e',
  },
  gameTitle: {
    fontSize: 36,
    fontWeight: 'bold',
    color: '#00d4ff',
    marginBottom: 10,
  },
  gameSubtitle: {
    fontSize: 18,
    color: '#ffffff',
    opacity: 0.8,
  },
  gameContent: {
    flex: 1,
    padding: 30,
    justifyContent: 'center',
  },
  gameDescription: {
    fontSize: 16,
    color: '#ffffff',
    textAlign: 'center',
    lineHeight: 24,
    marginBottom: 40,
  },
  downloadButton: {
    backgroundColor: '#00d4ff',
    padding: 20,
    borderRadius: 10,
    alignItems: 'center',
    marginBottom: 40,
  },
  downloadText: {
    fontSize: 20,
    fontWeight: 'bold',
    color: '#000000',
  },
  downloadSubtext: {
    fontSize: 14,
    color: '#000000',
    opacity: 0.7,
    marginTop: 5,
  },
  gameFeatures: {
    alignItems: 'center',
  },
  featureText: {
    fontSize: 16,
    color: '#ffffff',
    marginBottom: 10,
  },
  glitchBackground: {
    backgroundColor: '#ff0000',
  },
  terminalContainer: {
    flex: 1,
    padding: 20,
    justifyContent: 'center',
  },
  terminalText: {
    color: '#00ff00',
    fontSize: 16,
    fontFamily: 'monospace',
    lineHeight: 24,
  },
  cursor: {
    color: '#00ff00',
    fontSize: 16,
    fontFamily: 'monospace',
  },
  warningOverlay: {
    position: 'absolute',
    top: 0,
    left: 0,
    right: 0,
    bottom: 0,
    backgroundColor: 'rgba(255, 0, 0, 0.3)',
    justifyContent: 'center',
    alignItems: 'center',
  },
  warningText: {
    color: '#ffffff',
    fontSize: 24,
    fontWeight: 'bold',
    textAlign: 'center',
  },
  header: {
    padding: 20,
    paddingTop: 60,
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
  },
  headerText: {
    color: '#ff0000',
    fontSize: 20,
    fontWeight: 'bold',
  },
  subHeaderText: {
    color: '#ff0000',
    fontSize: 12,
  },
  vaultRoom: {
    flex: 1,
    padding: 20,
    justifyContent: 'center',
  },
  roomTitle: {
    color: '#ff0000',
    fontSize: 24,
    fontWeight: 'bold',
    textAlign: 'center',
    marginBottom: 5,
  },
  roomSubtitle: {
    color: '#ff0000',
    fontSize: 14,
    textAlign: 'center',
    marginBottom: 30,
  },
  vaultGrid: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    justifyContent: 'space-around',
    marginBottom: 30,
  },
  vaultPanel: {
    width: 80,
    height: 80,
    backgroundColor: '#ff0000',
    justifyContent: 'center',
    alignItems: 'center',
    margin: 5,
    borderRadius: 10,
  },
  panelText: {
    fontSize: 24,
    marginBottom: 5,
  },
  panelLabel: {
    fontSize: 10,
    fontWeight: 'bold',
    color: '#ffffff',
  },
  centerPanel: {
    width: 120,
    height: 120,
    backgroundColor: '#ff0000',
    justifyContent: 'center',
    alignItems: 'center',
    alignSelf: 'center',
    borderRadius: 15,
    borderWidth: 3,
    borderColor: '#ffff00',
  },
  centerText: {
    fontSize: 36,
    color: '#ffffff',
    marginBottom: 5,
  },
  centerLabel: {
    fontSize: 12,
    fontWeight: 'bold',
    color: '#ffffff',
  },
  alarmOverlay: {
    position: 'absolute',
    top: 0,
    left: 0,
    right: 0,
    bottom: 0,
    backgroundColor: 'rgba(255, 0, 0, 0.8)',
    justifyContent: 'center',
    alignItems: 'center',
  },
  alarmText: {
    color: '#ffffff',
    fontSize: 18,
    fontWeight: 'bold',
    marginBottom: 10,
    textAlign: 'center',
  },
  footer: {
    padding: 20,
    alignItems: 'center',
  },
  footerText: {
    color: '#ff0000',
    fontSize: 14,
  },
  progressContainer: {
    position: 'absolute',
    bottom: 20,
    left: 20,
    right: 20,
    alignItems: 'center',
  },
  progressText: {
    color: '#00ff00',
    fontSize: 12,
    fontFamily: 'monospace',
  },
  glitchOverlay: {
    position: 'absolute',
    top: 0,
    left: 0,
    right: 0,
    bottom: 0,
    backgroundColor: 'rgba(255, 0, 0, 0.1)',
  },
  glitchPixel: {
    position: 'absolute',
    width: 4,
    height: 4,
    backgroundColor: '#ff0000',
  },
  glitchText: {
    color: '#ff0000',
    fontSize: 16,
    fontWeight: 'bold',
    textAlign: 'center',
    fontFamily: 'monospace',
  },
  glitchContainer: {
    position: 'absolute',
    top: 0,
    left: 0,
    right: 0,
    bottom: 0,
    justifyContent: 'center',
    alignItems: 'center',
  },
}); 